-- CreateTable
CREATE TABLE "Bookshelf" (
    "BOOKSHELF_ID" SERIAL NOT NULL,
    "NAME" TEXT NOT NULL,

    CONSTRAINT "Bookshelf_pkey" PRIMARY KEY ("BOOKSHELF_ID")
);

-- CreateTable
CREATE TABLE "Books" (
    "BOOK_ID" SERIAL NOT NULL,
    "TITLE" TEXT NOT NULL,
    "AUTHOR" TEXT NOT NULL,
    "RELEASE_YEAR" INTEGER NOT NULL,
    "BOOKSHELF_ID" INTEGER NOT NULL,

    CONSTRAINT "Books_pkey" PRIMARY KEY ("BOOK_ID")
);

-- CreateTable
CREATE TABLE "Students" (
    "STUDENT_ID" SERIAL NOT NULL,
    "NIK" TEXT NOT NULL,
    "STUDENT_NAME" TEXT NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL,

    CONSTRAINT "Students_pkey" PRIMARY KEY ("STUDENT_ID")
);

-- CreateTable
CREATE TABLE "Transaction" (
    "TRANSACTION_ID" SERIAL NOT NULL,
    "STUDENT_ID" INTEGER NOT NULL,
    "TRANSACTION_DATE" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("TRANSACTION_ID")
);

-- CreateTable
CREATE TABLE "Transaction_Books" (
    "TRANSACTION_BOOKS_ID" SERIAL NOT NULL,
    "TRANSACTION_ID" INTEGER NOT NULL,
    "STUDENT_ID" INTEGER NOT NULL,
    "BOOK_ID" INTEGER NOT NULL,
    "START_DATE" TIMESTAMP(3) NOT NULL,
    "RETURN_DATE" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Transaction_Books_pkey" PRIMARY KEY ("TRANSACTION_BOOKS_ID")
);

-- CreateTable
CREATE TABLE "History" (
    "HISTORY_ID" SERIAL NOT NULL,
    "TRANSACTION_ID" INTEGER NOT NULL,
    "STUDENT_ID" INTEGER NOT NULL,
    "BOOK_ID" INTEGER NOT NULL,
    "START_DATE" TIMESTAMP(3) NOT NULL,
    "EXACT_RETURN_DATE" TIMESTAMP(3) NOT NULL,
    "INITIAL_RETURN_DATE" TIMESTAMP(3),
    "BORROWINGG_TIME" TEXT,

    CONSTRAINT "History_pkey" PRIMARY KEY ("HISTORY_ID")
);

-- AddForeignKey
ALTER TABLE "Books" ADD CONSTRAINT "Books_BOOKSHELF_ID_fkey" FOREIGN KEY ("BOOKSHELF_ID") REFERENCES "Bookshelf"("BOOKSHELF_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_STUDENT_ID_fkey" FOREIGN KEY ("STUDENT_ID") REFERENCES "Students"("STUDENT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction_Books" ADD CONSTRAINT "Transaction_Books_TRANSACTION_ID_fkey" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "Transaction"("TRANSACTION_ID") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Transaction_Books" ADD CONSTRAINT "Transaction_Books_STUDENT_ID_fkey" FOREIGN KEY ("STUDENT_ID") REFERENCES "Students"("STUDENT_ID") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Transaction_Books" ADD CONSTRAINT "Transaction_Books_BOOK_ID_fkey" FOREIGN KEY ("BOOK_ID") REFERENCES "Books"("BOOK_ID") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_TRANSACTION_ID_fkey" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "Transaction"("TRANSACTION_ID") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_STUDENT_ID_fkey" FOREIGN KEY ("STUDENT_ID") REFERENCES "Students"("STUDENT_ID") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_BOOK_ID_fkey" FOREIGN KEY ("BOOK_ID") REFERENCES "Books"("BOOK_ID") ON DELETE RESTRICT ON UPDATE NO ACTION;
